# Copyright 2026 Gautham Anil
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
The ISRO simulator's search functions, VERBATIM. Do not edit.

GENERATED by ``docs/data/lab1b/vendor_isro.py`` from
``GauthamCodes/isro-factory-pathfinding-simulator`` at commit ``5aad7b3e1b461ccb464667edc9cee59fa1d5a01b``, file ``astar_simulator_final_v3_6.py``
(SHA-256 ``ba05a8f3d8c1e42422d99e3bbdff840fa727ada6287661a8123f5501bd16abdb``), itself a transcription of the code listing in
the internship report. Every block between ``# >>> upstream`` and
``# <<< upstream`` markers is copied byte for byte from the upstream line
range it names; ``UPSTREAM_SEGMENTS`` records each block's SHA-256 and
``coco_lab/test/test_isro.py`` checks them on every run.

What is ours, above the first marker: this docstring, the imports the
functions use, and the module globals they read, which
:mod:`coco_lab.isro.historical` sets before each call. Pygame, drawing,
animation, file I/O and the event loop are not vendored; the search, cost,
heuristic, neighbour, reconstruction and smoothing code is.

The verbatim code keeps its original style, so this file is excluded from
the flake8 and pep257 linters (``test_flake8.py``, ``test_pep257.py``).
"""

import heapq
import math
import time
from collections import deque
from itertools import count

UPSTREAM_REPO = 'GauthamCodes/isro-factory-pathfinding-simulator'
UPSTREAM_COMMIT = '5aad7b3e1b461ccb464667edc9cee59fa1d5a01b'
UPSTREAM_PATH = 'astar_simulator_final_v3_6.py'
UPSTREAM_FILE_SHA256 = 'ba05a8f3d8c1e42422d99e3bbdff840fa727ada6287661a8123f5501bd16abdb'

#: (first line, last line) -> SHA-256 of the verbatim block.
UPSTREAM_SEGMENTS = {
    (53, 65): '1074f52b72cf6440572a0dbcceb277680fbd9b66e3ce2d9a2402ea93acb0ad1b',
    (107, 107): 'a8c37816ebe924d1701f334aaa740933207bba24f903d07e190f6ed4c3a8e66f',
    (110, 127): '5187bf50796a34d551e252da391477772d3363e350235a293a5d9c3f3a85ad74',
    (130, 135): '3f7f21667ffd03d145c678198079e6e7905f37897739950a9950b4aa43e220cf',
    (139, 143): '1f93299f3e3e2455b63ee77788ae9600eb112bc3b8ba0308f8c5e755ab9405b6',
    (147, 275): '71a2494c78f6583953d1c761db309e74980eae4e63022b5aa6540030090f0e34',
    (286, 322): 'e5caea73b8efa46eca44512c3f2b9967b6d5ab5fe9a58a719d0f075173d1f653',
}

# -- module globals the verbatim functions read (ours; set by historical.py)
ROWS, COLS = 30, 30          # upstream l.16
TURN_PENALTY = 0.1           # upstream l.20
grid = []                    # upstream l.89 builds it; historical.load does
static_obstacles = set()     # upstream l.90
dynamic_obstacles = []       # upstream l.90
CURRENT_EXPLORER = None      # upstream l.104


# >>> upstream l.53-65: class Cell (without draw(), which needs pygame)
class Cell:
    def __init__(self, r, c):
        self.row, self.col = r, c
        self.explored_by = None
        self.reset()

    def reset(self):
        self.type = 'empty'
        self.g = self.f = float('inf')
        self.parent = None
        self.direction = None
        self.explored_by = None
        self.explored_by_algo = None
# <<< upstream l.53-65


# >>> upstream l.107-107: DIRS
DIRS = [(-1, 0), (1, 0), (0, -1), (0, 1), (-1, -1), (-1, 1), (1, -1), (1, 1)]
# <<< upstream l.107-107


# >>> upstream l.110-127: heuristic, direction, move_cost, neighbors
def heuristic(a, b):
    dx, dy = abs(a.row - b.row), abs(a.col - b.col)
    return dx + dy + (math.sqrt(2) - 2) * min(dx, dy)


def direction(a, b):
    return (b.row - a.row, b.col - a.col)


def move_cost(a, b):
    return math.sqrt(2) if abs(a.row - b.row) and abs(a.col - b.col) else 1


def neighbors(cell):
    for dx, dy in DIRS:
        r, c = cell.row + dx, cell.col + dy
        if 0 <= r < ROWS and 0 <= c < COLS:
            yield grid[r][c]
# <<< upstream l.110-127


# >>> upstream l.130-135: get_blocked_positions
def get_blocked_positions():
    blocked = set(static_obstacles)
    for dyn in dynamic_obstacles:
        r, c = dyn['pos']
        blocked.add((r, c))
    return blocked
# <<< upstream l.130-135


# >>> upstream l.139-143: mark_cell_explored
def mark_cell_explored(cell, algo_label):
    if CURRENT_EXPLORER is None:
        return
    cell.explored_by = CURRENT_EXPLORER
    cell.explored_by_algo = algo_label
# <<< upstream l.139-143


# >>> upstream l.147-275: astar, dijkstra, bfs
def astar(start_pos, goal_pos):
    counter = count()
    open_set = []
    start = grid[start_pos[0]][start_pos[1]]
    goal = grid[goal_pos[0]][goal_pos[1]]
    for row in grid:
        for cell in row:
            cell.g = cell.f = float('inf')
            cell.parent = cell.direction = None
    start.g = 0
    start.f = heuristic(start, goal)
    heapq.heappush(open_set, (start.f, next(counter), start))
    blocked = get_blocked_positions()
    nodes = 0
    t0 = time.perf_counter()
    while open_set:
        f, _, curr = heapq.heappop(open_set)
        if f > curr.f:
            continue
        nodes += 1
        mark_cell_explored(curr, 'A*')
        if curr == goal:
            break
        for nbr in neighbors(curr):
            pos = (nbr.row, nbr.col)
            if pos in blocked or nbr.type == 'obstacle':
                continue
            new_g = curr.g + move_cost(curr, nbr)
            if curr.direction and direction(curr, nbr) != curr.direction:
                new_g += TURN_PENALTY
            if new_g < nbr.g:
                nbr.g = new_g
                nbr.f = new_g + heuristic(nbr, goal)
                nbr.parent = curr
                nbr.direction = direction(curr, nbr)
                heapq.heappush(open_set, (nbr.f, next(counter), nbr))
    path, curr = [], goal
    total_len, turns = 0, 0
    last_dir = None
    while curr and curr != start:
        path.append(curr)
        if curr.parent:
            total_len += move_cost(curr, curr.parent)
            dir_now = direction(curr.parent, curr)
            if last_dir and dir_now != last_dir:
                turns += 1
            last_dir = dir_now
        curr = curr.parent
    path.reverse()
    return path, {'length': round(total_len, 2), 'turns': turns, 'explored': nodes, 'time': round(time.perf_counter() - t0, 4)}


def dijkstra(start_pos, goal_pos):
    counter = count()
    open_set = []
    start = grid[start_pos[0]][start_pos[1]]
    goal = grid[goal_pos[0]][goal_pos[1]]
    for row in grid:
        for cell in row:
            cell.g = float('inf')
            cell.parent = cell.direction = None
    start.g = 0
    heapq.heappush(open_set, (start.g, next(counter), start))
    visited = set()
    blocked = get_blocked_positions()
    nodes = 0
    t0 = time.perf_counter()
    while open_set:
        _, _, curr = heapq.heappop(open_set)
        nodes += 1
        mark_cell_explored(curr, 'Dijkstra')
        if curr == goal:
            break
        visited.add((curr.row, curr.col))
        for nbr in neighbors(curr):
            if (nbr.row, nbr.col) in visited or (nbr.row, nbr.col) in blocked or nbr.type == 'obstacle':
                continue
            new_g = curr.g + move_cost(curr, nbr)
            if curr.direction and direction(curr, nbr) != curr.direction:
                new_g += TURN_PENALTY
            if new_g < nbr.g:
                nbr.g = new_g
                nbr.parent = curr
                nbr.direction = direction(curr, nbr)
                heapq.heappush(open_set, (nbr.g, next(counter), nbr))
    path, curr = [], goal
    total_len, turns = 0, 0
    last_dir = None
    while curr and curr != start:
        path.append(curr)
        if curr.parent:
            total_len += move_cost(curr, curr.parent)
            dir_now = direction(curr.parent, curr)
            if last_dir and dir_now != last_dir:
                turns += 1
            last_dir = dir_now
        curr = curr.parent
    path.reverse()
    return path, {'length': round(total_len, 2), 'turns': turns, 'explored': nodes, 'time': round(time.perf_counter() - t0, 4)}


def bfs(start_pos, goal_pos):
    start = grid[start_pos[0]][start_pos[1]]
    goal = grid[goal_pos[0]][goal_pos[1]]
    for row in grid:
        for cell in row:
            cell.parent = None
    queue = deque([start])
    visited = {(start.row, start.col)}
    blocked = get_blocked_positions()
    t0 = time.perf_counter()
    while queue:
        curr = queue.popleft()
        mark_cell_explored(curr, 'BFS')
        if curr == goal:
            break
        for nbr in neighbors(curr):
            pos = (nbr.row, nbr.col)
            if pos in visited or pos in blocked or nbr.type == 'obstacle':
                continue
            visited.add(pos)
            nbr.parent = curr
            queue.append(nbr)
    path, curr = [], goal
    while curr and curr != start:
        path.append(curr)
        curr = curr.parent
    path.reverse()
    return path, {'length': len(path), 'turns': 0, 'explored': len(visited), 'time': round(time.perf_counter() - t0, 4)}
# <<< upstream l.147-275


# >>> upstream l.286-322: line_of_sight, smooth_path
def line_of_sight(a, b):
    x0, y0 = a.col, a.row
    x1, y1 = b.col, b.row
    dx, dy = abs(x1 - x0), abs(y1 - y0)
    x, y = x0, y0
    n = 1 + dx + dy
    x_inc = 1 if x1 > x0 else -1
    y_inc = 1 if y1 > y0 else -1
    error = dx - dy
    dx *= 2
    dy *= 2
    for _ in range(n):
        if grid[y][x].type == 'obstacle' or (y, x) in static_obstacles:
            return False
        if error > 0:
            x += x_inc
            error -= dy
        else:
            y += y_inc
            error += dx
    return True


def smooth_path(path):
    if not path:
        return path
    new_path = [path[0]]
    i = 0
    while i < len(path) - 1:
        j = len(path) - 1
        while j > i:
            if line_of_sight(path[i], path[j]):
                break
            j -= 1
        new_path.append(path[j])
        i = j
    return new_path
# <<< upstream l.286-322
