#!/usr/bin/env python3
# Copyright 2026 Gautham Anil
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Write ``worlds/coco_arena_v1.yaml`` from the files that define the arena.

    python3 worlds/tools/make_coco_arena_v1.py [--check]

Every number is read from its source, never typed here:

- geometry, bounds, resolution, world-to-map, ramp bays:
  ``gazebo_models/config/navigation_world.json`` (what the Stack's world
  and saved map are generated from);
- ramp grade, LiDAR mount, ground clearance, wheels, accelerations, spawn:
  ``coco_config/coco_config/robot.py`` (parsed, not imported: no ROS);
- LiDAR beams and range, collision radius: ``coco_lab/coco_lab/sketch.py``
  (``COCO_LIDAR``, ``ROBOT_RADIUS``, pinned to the xacro by
  ``coco_lab_ros/test/test_sketch_constants.py``);
- teleop limits: ``coco_web/coco_web/safety.py``; autonomous limits and the
  control rate: ``gazebo_models/config/nav2_params.yaml`` (FollowPath,
  controller_frequency).

``--check`` exits 1 if the committed YAML differs from a fresh one, so the
spec cannot drift from the frozen stack it describes (CI runs it through
``coco_lab_ros/test/test_world_spec_sources.py``).
"""

import argparse
import ast
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.realpath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
OUT = os.path.join(REPO, 'worlds', 'coco_arena_v1.yaml')
#: The canonical bytes (coco_lab.worldspec.canonical_bytes): what the browser
#: loads (Pyodide has no YAML parser) and what run_id hashes.
OUT_JSON = os.path.join(REPO, 'worlds', 'coco_arena_v1.json')
NAV_JSON = 'gazebo_models/config/navigation_world.json'
ROBOT_PY = 'coco_config/coco_config/robot.py'
SKETCH_PY = 'coco_lab/coco_lab/sketch.py'
SAFETY_PY = 'coco_web/coco_web/safety.py'
NAV2_YAML = 'gazebo_models/config/nav2_params.yaml'


def _read(rel):
    with open(os.path.join(REPO, rel), encoding='utf-8') as f:
        return f.read()


def constants(rel):
    """Return the module-level literal constants of a Python file."""
    out = {}
    for node in ast.parse(_read(rel)).body:
        if isinstance(node, ast.Assign) and len(node.targets) == 1 \
                and isinstance(node.targets[0], ast.Name):
            try:
                out[node.targets[0].id] = ast.literal_eval(node.value)
            except ValueError:
                pass
    return out


def lidar_from_sketch():
    """Return the keyword arguments of sketch.COCO_LIDAR."""
    for node in ast.parse(_read(SKETCH_PY)).body:
        if isinstance(node, ast.Assign) and getattr(
                node.targets[0], 'id', '') == 'COCO_LIDAR':
            return {k.arg: ast.literal_eval(k.value)
                    for k in node.value.keywords}
    raise SystemExit('COCO_LIDAR not found in sketch.py')


def nav2_value(key):
    """Return one scalar from nav2_params.yaml (first occurrence)."""
    m = re.search(rf'^\s*{key}:\s*([0-9.]+)\s*$', _read(NAV2_YAML), re.M)
    if not m:
        raise SystemExit(f'{key} not found in {NAV2_YAML}')
    return float(m.group(1))


def kind_of(name):
    """Classify a box by its name in navigation_world.json."""
    if name.startswith('wall_'):
        return 'wall'
    if 'landmark' in name:
        return 'landmark'
    if 'guard' in name or 'approach' in name:
        return 'guard'
    return 'obstacle'


def num(v):
    """Format a number as YAML, keeping integers integral."""
    return repr(float(v)) if isinstance(v, float) else str(v)


def build():
    """Return the YAML text."""
    nav = json.loads(_read(NAV_JSON))
    rb = constants(ROBOT_PY)
    sk = constants(SKETCH_PY)
    lidar = lidar_from_sketch()
    sf = constants(SAFETY_PY)
    xmin, xmax, ymin, ymax = nav['bounds']
    bay = nav['ramp_bays']
    lx, ly, lz = rb['LIDAR_MOUNT_XYZ']
    sx, sy = rb['SPAWN_XY']
    lines = [
        '# COCO arena, World Spec v1 (docs/v2/WORLD_SPEC.md).',
        '# GENERATED by worlds/tools/make_coco_arena_v1.py from the files',
        '# under `sources`; edit those and regenerate, never this file.',
        f'spec_version: coco.world_spec.v1',
        'id: coco_arena_v1',
        "title: COCO arena (the Gazebo navigation world, "
        f"{xmax - xmin:g} x {ymax - ymin:g} m)",
        'sources:',
        f'  geometry: {NAV_JSON}',
        f'  robot: {ROBOT_PY}',
        f'  lidar_and_radius: {SKETCH_PY} (COCO_LIDAR, ROBOT_RADIUS)',
        f'  teleop_limits: {SAFETY_PY}',
        f'  auto_limits_and_rate: {NAV2_YAML} (FollowPath, controller_frequency)',
        'notes: >-',
        '  Geometry is in the Gazebo world frame; the Arena and the Stack drive',
        '  in the map frame (world + world_to_map). Ramps are 3D in the Stack;',
        '  in the Arena a ramp is its footprint at the LiDAR scan height, as in',
        "  the Stack's saved map.",
        'frame: world',
        f'world_to_map: [{num(nav["world_to_map"][0])}, '
        f'{num(nav["world_to_map"][1])}]',
        'bounds: {'
        f'x_min: {num(xmin)}, x_max: {num(xmax)}, y_min: {num(ymin)}, '
        f'y_max: {num(ymax)}}}',
        'boxes:',
    ]
    for b in nav['boxes']:
        (x, y, z), (bx, by, bz) = b['pose'], b['size']
        lines.append(
            f'  - {{id: {b["name"]}, kind: {kind_of(b["name"])}, '
            f'center: [{num(x)}, {num(y)}], size: [{num(bx)}, {num(by)}], '
            f'z: {num(z)}, height: {num(bz)}}}')
    lines += [
        'ramps:',
        f'  angle_deg: {num(rb["RAMP_ANGLE_DEG"])}',
        f'  foot_x: {num(bay["foot_x"])}',
        f'  run: {num(bay["run"])}',
        f'  platform_length: {num(bay["platform_length"])}',
        f'  width: {num(bay["width"])}',
        '  centres_y: [' + ', '.join(num(c) for c in bay['centres_y']) + ']',
        'robot:',
        f'  wheel_radius: {num(rb["WHEEL_RADIUS"])}',
        f'  wheel_separation: {num(rb["WHEEL_SEPARATION"])}',
        f'  radius: {num(sk["ROBOT_RADIUS"])}',
        f'  ground_clearance: {num(rb["CHASSIS_GROUND_CLEARANCE"])}',
        '  limits:',
        f'    teleop_linear: {num(sf["MAX_LINEAR"])}',
        f'    teleop_angular: {num(sf["MAX_ANGULAR"])}',
        f'    auto_linear: {num(nav2_value("max_vel_x"))}',
        f'    auto_angular: {num(nav2_value("max_vel_theta"))}',
        f'    linear_accel: {num(rb["MAX_LINEAR_ACCEL"])}',
        f'    angular_accel: {num(rb["MAX_ANGULAR_ACCEL"])}',
        '  lidar:',
        f'    mount: [{num(lx)}, {num(ly)}, {num(lz)}]',
        f'    samples: {lidar["samples"]}',
        f'    angle_min: {num(lidar["angle_min"])}',
        f'    angle_max: {num(lidar["angle_max"])}',
        f'    range_min: {num(lidar["range_min"])}',
        f'    range_max: {num(lidar["range_max"])}',
        f'start: {{x: {num(sx)}, y: {num(sy)}, theta: 0.0}}',
        'arena:',
        f'  resolution: {num(nav["resolution"])}',
        '  margin: 0.5',
        f'  dt: {num(1.0 / nav2_value("controller_frequency"))}',
        '  unknown: blocked',
    ]
    return '\n'.join(lines) + '\n'


def canonical(text):
    """Return the spec's canonical bytes (needs PyYAML and coco_lab)."""
    import yaml
    sys.path.insert(0, os.path.join(REPO, 'coco_lab'))
    from coco_lab.worldspec import canonical_bytes
    return canonical_bytes(yaml.safe_load(text))


def main(argv=None):
    """Write the YAML and its canonical JSON, or check both are current."""
    ap = argparse.ArgumentParser(description=__doc__.split('\n')[1])
    ap.add_argument('--check', action='store_true')
    a = ap.parse_args(argv)
    text = build()
    data = canonical(text)
    if a.check:
        with open(OUT, encoding='utf-8') as f:
            stale = f.read() != text
        with open(OUT_JSON, 'rb') as f:
            stale = stale or f.read() != data
        if stale:
            print('STALE: worlds/coco_arena_v1.yaml or .json differs from '
                  'its sources; run worlds/tools/make_coco_arena_v1.py',
                  file=sys.stderr)
            return 1
        print('worlds/coco_arena_v1.yaml and .json are current')
        return 0
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write(text)
    with open(OUT_JSON, 'wb') as f:
        f.write(data)
    print(f'wrote {os.path.relpath(OUT, REPO)} and its canonical JSON')
    return 0


if __name__ == '__main__':
    sys.exit(main())
