#!/usr/bin/env python3
# Copyright 2026 Gautham Anil
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Generate coco_schemas' Python and TypeScript code from its .proto files.

    python3 coco_schemas/scripts/generate.py [--lang py|ts|all] [--check]

Python: ``protoc --python_out`` into ``coco_schemas/coco_schemas/gen/``,
with the generated ``from coco.<pkg> import x_pb2`` imports rewritten to
``from coco_schemas.gen.coco.<pkg> import x_pb2`` so the code is importable
as part of this package. TypeScript: ``protoc-gen-es`` (lab_web's pinned
devDependency) into ``lab_web/src/schemas/gen/``.

``--check`` regenerates into a temporary directory and fails if anything
differs from what is committed: CI runs it, so generated code is never
stale. The generator pins nothing itself; the protoc it found is recorded
in every Python file's header and checked against ``PROTOC_VERSION``.
"""

import argparse
import filecmp
import os
import re
import shutil
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.realpath(__file__))
PKG = os.path.dirname(HERE)                      # coco_schemas/
REPO = os.path.dirname(PKG)
PROTO = os.path.join(PKG, 'proto')
PY_OUT = os.path.join(PKG, 'coco_schemas', 'gen')
TS_OUT = os.path.join(REPO, 'lab_web', 'src', 'schemas', 'gen')
PLUGIN = os.path.join(REPO, 'lab_web', 'node_modules', '.bin', 'protoc-gen-es')
#: The protoc the committed code was generated with (Ubuntu 24.04's
#: protobuf-compiler, the same one CI installs).
PROTOC_VERSION = 'libprotoc 3.21.12'
PY_HEADER = ('# Generated by coco_schemas/scripts/generate.py from {src} '
             '({protoc}). DO NOT EDIT.\n')
IMPORT = re.compile(r'^from coco(\.[\w.]+) import ', re.M)


def protos():
    """Return every .proto file, relative to PROTO, sorted."""
    out = []
    for d, _, names in os.walk(PROTO):
        out += [os.path.relpath(os.path.join(d, n), PROTO)
                for n in names if n.endswith('.proto')]
    return sorted(out)


def protoc_version():
    """Return protoc's version line; fail if it is not the pinned one."""
    v = subprocess.run(['protoc', '--version'], capture_output=True,
                       text=True, check=True).stdout.strip()
    if v != PROTOC_VERSION:
        sys.exit(f'protoc is "{v}", expected "{PROTOC_VERSION}" '
                 '(apt install protobuf-compiler on Ubuntu 24.04)')
    return v


def gen_py(out):
    """Generate the Python package tree under ``out``."""
    version = protoc_version()
    with tempfile.TemporaryDirectory() as raw:
        subprocess.run(['protoc', f'-I{PROTO}', f'--python_out={raw}']
                       + protos(), check=True, cwd=PROTO)
        for d, _, names in os.walk(raw):
            rel = os.path.relpath(d, raw)
            dst = os.path.join(out, rel)
            os.makedirs(dst, exist_ok=True)
            for n in names:
                with open(os.path.join(d, n)) as f:
                    text = f.read()
                text = IMPORT.sub(r'from coco_schemas.gen.coco\1 import ', text)
                src = os.path.join(rel, n).replace('_pb2.py', '.proto')
                with open(os.path.join(dst, n), 'w') as f:
                    f.write(PY_HEADER.format(src=src, protoc=version) + text)
    # every directory is a package
    for d, _, _ in os.walk(out):
        init = os.path.join(d, '__init__.py')
        if not os.path.exists(init):
            with open(init, 'w') as f:
                f.write('# Generated by coco_schemas/scripts/generate.py. '
                        'DO NOT EDIT.\n')


def gen_ts(out):
    """Generate the TypeScript tree under ``out`` with protoc-gen-es."""
    protoc_version()
    if not os.path.exists(PLUGIN):
        sys.exit(f'{PLUGIN} is missing: run `npm ci` in lab_web')
    os.makedirs(out, exist_ok=True)
    subprocess.run(['protoc', f'-I{PROTO}', f'--plugin=protoc-gen-es={PLUGIN}',
                    f'--es_out={out}',
                    '--es_opt=target=ts,import_extension=none']
                   + protos(), check=True, cwd=PROTO)


def descriptor_set(path):
    """Write every .proto's FileDescriptorSet (with imports) to ``path``."""
    protoc_version()
    subprocess.run(['protoc', f'-I{PROTO}', f'--descriptor_set_out={path}',
                    '--include_imports'] + protos(), check=True, cwd=PROTO)


def _walk(root):
    """os.walk without __pycache__ (bytecode is not generated code)."""
    for d, dirs, names in os.walk(root):
        dirs[:] = [x for x in dirs if x != '__pycache__']
        yield d, dirs, [n for n in names if not n.endswith('.pyc')]


def same_tree(a, b):
    """Return the list of differing relative paths between two trees."""
    diffs = []
    for root, other in ((a, b), (b, a)):
        for d, _, names in _walk(root):
            for n in names:
                rel = os.path.relpath(os.path.join(d, n), root)
                if not os.path.exists(os.path.join(other, rel)):
                    diffs.append(rel)
    for d, _, names in _walk(a):
        for n in names:
            rel = os.path.relpath(os.path.join(d, n), a)
            o = os.path.join(b, rel)
            if os.path.exists(o) and not filecmp.cmp(os.path.join(d, n), o,
                                                     shallow=False):
                diffs.append(rel)
    return sorted(set(diffs))


def main(argv=None):
    """Generate, or check that the committed code is current."""
    ap = argparse.ArgumentParser(description=__doc__.split('\n')[1])
    ap.add_argument('--lang', choices=('py', 'ts', 'all'), default='all')
    ap.add_argument('--check', action='store_true')
    ap.add_argument('--descriptor-set', metavar='PATH',
                    help='only write the FileDescriptorSet to PATH')
    ap.add_argument('--write-baseline', action='store_true',
                    help='write compat/v1.binpb (only when a major starts)')
    a = ap.parse_args(argv)
    if a.descriptor_set:
        descriptor_set(os.path.abspath(a.descriptor_set))
        return 0
    if a.write_baseline:
        descriptor_set(os.path.join(PKG, 'compat', 'v1.binpb'))
        print('wrote coco_schemas/compat/v1.binpb')
        return 0
    jobs = [(gen_py, PY_OUT)] if a.lang in ('py', 'all') else []
    jobs += [(gen_ts, TS_OUT)] if a.lang in ('ts', 'all') else []
    bad = []
    for fn, dest in jobs:
        if a.check:
            with tempfile.TemporaryDirectory() as tmp:
                fn(tmp)
                diffs = same_tree(tmp, dest) if os.path.isdir(dest) else ['*']
            if diffs:
                bad.append((dest, diffs))
        else:
            if os.path.isdir(dest):
                shutil.rmtree(dest)
            fn(dest)
            print(f'generated {os.path.relpath(dest, REPO)}')
    for dest, diffs in bad:
        print(f'STALE: {os.path.relpath(dest, REPO)} differs from a fresh '
              f'generation: {diffs[:10]}', file=sys.stderr)
    if bad:
        print('run: python3 coco_schemas/scripts/generate.py', file=sys.stderr)
        return 1
    if a.check:
        print('generated code is current')
    return 0


if __name__ == '__main__':
    sys.exit(main())
