# Copyright 2026 Gautham Anil
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Vendor the ISRO simulator's search functions into coco_lab, verbatim.

Reads ``astar_simulator_final_v3_6.py`` at a pinned commit of the private
repository ``GauthamCodes/isro-factory-pathfinding-simulator`` (through
``gh api``, which needs the owner's authentication, or from a local copy
with ``--source``), checks the whole file's SHA-256, cuts out the listed
line ranges, and writes ``coco_lab/coco_lab/isro/upstream_v3_6.py``: our
header and preamble, then each range byte for byte between marker
comments, with the SHA-256 of every range recorded in the file.
``coco_lab/test/test_isro.py`` re-hashes the ranges on every run, so an
edit to the vendored code fails the suite.

Usage (from the repository root)::

    python3 docs/data/lab1b/vendor_isro.py            # fetch with gh
    python3 docs/data/lab1b/vendor_isro.py --source astar_simulator_final_v3_6.py
    python3 docs/data/lab1b/vendor_isro.py --check    # verify, write nothing
"""

import argparse
import hashlib
import os
import subprocess
import sys

REPO = 'GauthamCodes/isro-factory-pathfinding-simulator'
COMMIT = '5aad7b3e1b461ccb464667edc9cee59fa1d5a01b'
PATH = 'astar_simulator_final_v3_6.py'

#: (first line, last line, what) -- 1-based, inclusive, upstream numbering.
SEGMENTS = (
    (53, 65, 'class Cell (without draw(), which needs pygame)'),
    (107, 107, 'DIRS'),
    (110, 127, 'heuristic, direction, move_cost, neighbors'),
    (130, 135, 'get_blocked_positions'),
    (139, 143, 'mark_cell_explored'),
    (147, 275, 'astar, dijkstra, bfs'),
    (286, 322, 'line_of_sight, smooth_path'),
)

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.normpath(os.path.join(HERE, '..', '..', '..', 'coco_lab',
                                    'coco_lab', 'isro', 'upstream_v3_6.py'))

HEADER = '''# Copyright 2026 Gautham Anil
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
The ISRO simulator's search functions, VERBATIM. Do not edit.

GENERATED by ``docs/data/lab1b/vendor_isro.py`` from
``{repo}`` at commit ``{commit}``, file ``{path}``
(SHA-256 ``{file_sha}``), itself a transcription of the code listing in
the internship report. Every block between ``# >>> upstream`` and
``# <<< upstream`` markers is copied byte for byte from the upstream line
range it names; ``UPSTREAM_SEGMENTS`` records each block's SHA-256 and
``coco_lab/test/test_isro.py`` checks them on every run.

What is ours, above the first marker: this docstring, the imports the
functions use, and the module globals they read, which
:mod:`coco_lab.isro.historical` sets before each call. Pygame, drawing,
animation, file I/O and the event loop are not vendored; the search, cost,
heuristic, neighbour, reconstruction and smoothing code is.

The verbatim code keeps its original style, so this file is excluded from
the flake8 and pep257 linters (``test_flake8.py``, ``test_pep257.py``).
"""

import heapq
import math
import time
from collections import deque
from itertools import count

UPSTREAM_REPO = {repo!r}
UPSTREAM_COMMIT = {commit!r}
UPSTREAM_PATH = {path!r}
UPSTREAM_FILE_SHA256 = {file_sha!r}

#: (first line, last line) -> SHA-256 of the verbatim block.
UPSTREAM_SEGMENTS = {{
{segment_table}}}

# -- module globals the verbatim functions read (ours; set by historical.py)
ROWS, COLS = 30, 30          # upstream l.16
TURN_PENALTY = 0.1           # upstream l.20
grid = []                    # upstream l.89 builds it; historical.load does
static_obstacles = set()     # upstream l.90
dynamic_obstacles = []       # upstream l.90
CURRENT_EXPLORER = None      # upstream l.104
'''


def fetch() -> bytes:
    """Return the upstream file's bytes at COMMIT, via ``gh api``."""
    return subprocess.run(
        ['gh', 'api', '-H', 'Accept: application/vnd.github.raw',
         f'repos/{REPO}/contents/{PATH}?ref={COMMIT}'],
        capture_output=True, check=True, timeout=60).stdout


def render(source: bytes) -> str:
    """Return the vendored module's text for ``source``."""
    text = source.decode('utf-8')
    lines = text.splitlines(keepends=True)
    blocks, table = [], []
    for first, last, what in SEGMENTS:
        seg = ''.join(lines[first - 1:last])
        digest = hashlib.sha256(seg.encode('utf-8')).hexdigest()
        table.append(f'    ({first}, {last}): {digest!r},\n')
        blocks.append(f'\n\n# >>> upstream l.{first}-{last}: {what}\n'
                      f'{seg}# <<< upstream l.{first}-{last}\n')
    head = HEADER.format(repo=REPO, commit=COMMIT, path=PATH,
                         file_sha=hashlib.sha256(source).hexdigest(),
                         segment_table=''.join(table))
    return head + ''.join(blocks)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split('\n')[1])
    ap.add_argument('--source', help='a local copy of the upstream file')
    ap.add_argument('--check', action='store_true',
                    help='compare with the committed file; write nothing')
    args = ap.parse_args(argv)
    if args.source:
        with open(args.source, 'rb') as f:
            source = f.read()
    else:
        source = fetch()
    print(f'upstream {PATH} @ {COMMIT[:7]}: {len(source)} bytes, '
          f'sha256 {hashlib.sha256(source).hexdigest()}')
    text = render(source)
    if args.check:
        with open(OUT, encoding='utf-8') as f:
            same = f.read() == text
        print('vendored file matches upstream' if same else
              'vendored file DIFFERS from upstream')
        return 0 if same else 1
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write(text)
    print(f'wrote {OUT}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
