# Copyright 2026 Gautham Anil
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Write what the TypeScript decoder must reproduce, from ``coco_lab`` itself.

Three committed outputs, all regenerated byte-for-byte by
``test_tools.py`` so they cannot drift from the Python reference:

``test/golden/expected.json``
    For each of the nine decoder bundles (six golden fixtures, three 1C
    runs): version, hashes, header and summary, every array's count,
    sha256 of its little-endian bytes and first/last values, the recording
    block, cursor checkpoints under the display rule (``common.py``),
    hover samples, and ``LabMap.cell_at`` for every planned-path point --
    the orientation oracle.
``test/invalid/``
    The invalid-bundle corpus (``invalid_corpus.py``).
``test/golden/json_corpus.json``
    The canonical-JSON corpus (``json_corpus.py``).

Usage (from anywhere; ``coco_lab`` must be importable, no ROS needed)::

    python3 lab_web/tools/make_expectations.py            # write
    python3 lab_web/tools/make_expectations.py --check    # compare only
"""

import argparse
import filecmp
import json
import os
import random
import shutil
import struct
import sys
import tempfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from coco_lab import bundle  # noqa: E402
from coco_lab.maps import MapError  # noqa: E402
import common  # noqa: E402
import invalid_corpus  # noqa: E402
import json_corpus  # noqa: E402

EXPECTED = os.path.join(common.LAB_WEB, 'test', 'golden', 'expected.json')
JSON_CORPUS = os.path.join(common.LAB_WEB, 'test', 'golden',
                           'json_corpus.json')
INVALID = os.path.join(common.LAB_WEB, 'test', 'invalid')

HOVER_SAMPLES = 12
SEED = 1729


def _first_last(values):
    if not values:
        return None, None
    return values[0], values[-1]


def expect_bundle(bid: str, rel: str) -> dict:
    """Return the expectation record of one bundle directory."""
    path = os.path.join(common.REPO, rel)
    mtext, aname, adata, raw = common.read_files(path)
    manifest = json.loads(mtext)
    b = bundle.load_bundle(path)
    ev = b.trace.events
    n = len(b.trace)
    m = b.lab_map

    arrays = {}
    for a in manifest['arrays']:
        chunk = raw[a['offset']:a['offset'] + a['byte_length']]
        code = bundle.DTYPES[a['dtype']][0]
        values = list(struct.unpack(f'<{a["count"]}{code}', chunk))
        first, last = _first_last(values)
        arrays[a['name']] = {
            'dtype': a['dtype'], 'count': a['count'],
            'offset': a['offset'], 'byte_length': a['byte_length'],
            'sha256': common.sha256_hex(chunk),
            'first': first, 'last': last,
        }

    cursor = []
    for k in sorted({0, n // 4, n // 2, (3 * n) // 4, n}):
        s = common.cell_states(ev, m.width, m.height, k)
        cursor.append({
            'k': k, 'sha256': common.sha256_hex(bytes(s)),
            'open': s.count(1), 'closed': s.count(2), 'path': s.count(3)})

    rng = random.Random(f'{SEED}:{bid}')
    samples = []
    start = b.run['start']
    samples.append((start[0], start[1], n))
    samples.append((start[0], start[1], 0))
    for _ in range(HOVER_SAMPLES):
        i = rng.randrange(n)
        k = rng.randint(i, n)
        samples.append((ev['row'][i], ev['col'][i], k))
    # a cell no event touches, if there is one
    touched = {(r, c) for r, c in zip(ev['row'], ev['col'])}
    for r in range(m.height):
        free = [c for c in range(m.width) if (r, c) not in touched]
        if free:
            samples.append((r, free[0], n))
            break
    hover = [{'row': r, 'col': c, 'k': k,
              'states': common.hover(ev, r, c, k)} for r, c, k in samples]

    orientation = None
    if m.has_geo:
        orientation = {'start_centre': list(m.cell_centre(*start)),
                       'goal_centre': list(m.cell_centre(*b.run['goal']))}
        if b.streams and 'plan' in b.streams:
            p = b.streams['plan']
            orientation['plan_cells'] = [
                (list(cell) if cell is not None else None)
                for cell in (m.cell_at(x, y) for x, y in zip(p['x'], p['y']))]
    else:
        try:
            m.cell_at(0.0, 0.0)
            raise AssertionError('a map without geo placed a point')
        except MapError:
            pass

    rec = None
    if b.recording is not None:
        rec = {'groups': b.recording['groups'],
               'missing': b.recording['missing'],
               'run_id': b.recording['run_id']}

    return {
        'id': bid,
        'dir': rel,
        'arrays_file': aname,
        'file_bytes': {'manifest': len(mtext), 'arrays': len(adata),
                       'raw': len(raw)},
        'version': manifest['version'],
        'source_kind': manifest['provenance']['source_kind'],
        'content_hash': manifest['content_hash'],
        'computed_content_hash': bundle.content_hash(manifest, raw),
        'map_hash': m.content_hash(),
        'width': m.width, 'height': m.height,
        'cost_layer': m.cost is not None,
        'geo': manifest['map']['geo'],
        'header': b.trace.header,
        'summary': b.trace.summary,
        'run': b.run,
        'events': n,
        'arrays': arrays,
        'recording': rec,
        'cursor': cursor,
        'hover': hover,
        'orientation': orientation,
    }


def expectations() -> dict:
    """Return the full expected.json document."""
    return {
        'generator': 'lab_web/tools/make_expectations.py',
        'display_rule': 'max over events i < k at the cell of '
                        'push=1 expand=2 relax=1 path=3',
        'bundles': [expect_bundle(bid, rel)
                    for bid, rel in common.bundle_sources()],
    }


def _dump(obj) -> str:
    return json.dumps(obj, indent=1, sort_keys=True, allow_nan=False) + '\n'


def write_all(root: str) -> None:
    """Write every committed output under ``root`` (a lab_web copy)."""
    golden = os.path.join(root, 'test', 'golden')
    os.makedirs(golden, exist_ok=True)
    with open(os.path.join(golden, 'expected.json'), 'w') as f:
        f.write(_dump(expectations()))
    with open(os.path.join(golden, 'json_corpus.json'), 'w') as f:
        f.write(_dump(json_corpus.corpus()))
    invalid = os.path.join(root, 'test', 'invalid')
    if os.path.isdir(invalid):
        shutil.rmtree(invalid)
    invalid_corpus.write(invalid)


def _same_tree(a: str, b: str) -> list:
    cmp = filecmp.dircmp(a, b)
    diffs = [os.path.join(a, x) for x in
             cmp.left_only + cmp.right_only + cmp.diff_files + cmp.funny_files]
    for sub in cmp.common_dirs:
        diffs += _same_tree(os.path.join(a, sub), os.path.join(b, sub))
    return diffs


def check() -> list:
    """Regenerate into a temp dir; return the paths that differ."""
    tmp = tempfile.mkdtemp()
    try:
        write_all(tmp)
        diffs = []
        for rel in (('test', 'golden', 'expected.json'),
                    ('test', 'golden', 'json_corpus.json')):
            ours = os.path.join(common.LAB_WEB, *rel)
            if not (os.path.exists(ours) and filecmp.cmp(
                    ours, os.path.join(tmp, *rel), shallow=False)):
                diffs.append(os.path.join(*rel))
        if not os.path.isdir(INVALID):
            diffs.append('test/invalid')
        else:
            diffs += _same_tree(INVALID, os.path.join(tmp, 'test', 'invalid'))
        return diffs
    finally:
        shutil.rmtree(tmp)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split('\n')[1])
    ap.add_argument('--check', action='store_true')
    args = ap.parse_args(argv)
    if args.check:
        diffs = check()
        for d in diffs:
            print(f'DIFFERS: {d}')
        return 1 if diffs else 0
    write_all(common.LAB_WEB)
    print(f'wrote {EXPECTED}, {JSON_CORPUS}, {INVALID}/')
    return 0


if __name__ == '__main__':
    sys.exit(main())
