# Copyright 2026 Gautham Anil
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Write what lab_web's search-bundle decoder must reproduce, from coco_lab.

``test/golden/search_expected.json``: for each golden search bundle
(``coco_lab/test/fixtures/search_bundles``) the version and content hash,
the problem's region ids, and for EVERY array its count, the sha256 of its
little-endian bytes and its first and last values (``nan`` as the string
``"nan"``); for every run its id, kind and summary. Regenerated byte for
byte by ``test_tools.py``, so it cannot drift.

Usage (``coco_lab`` importable, no ROS)::

    python3 lab_web/tools/make_search_expectations.py [--check]
"""

import argparse
import hashlib
import json
import math
import os
import struct
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from coco_lab import searchbundle  # noqa: E402
import common  # noqa: E402

FIXTURES = os.path.join('coco_lab', 'test', 'fixtures', 'search_bundles')
OUT = os.path.join(common.LAB_WEB, 'test', 'golden', 'search_expected.json')


def _v(x):
    if isinstance(x, float) and math.isnan(x):
        return 'nan'
    if isinstance(x, float) and math.isinf(x):
        return 'inf' if x > 0 else '-inf'
    return x


def expect(name):
    """Return the expectation record of one golden search bundle."""
    rel = os.path.join(FIXTURES, name)
    path = os.path.join(common.REPO, rel)
    manifest = json.loads(open(os.path.join(path, 'manifest.json'),
                               'rb').read())
    b = searchbundle.load_search_bundle(path)
    raw = b''.join(d for _, _, d in b.arrays())
    arrays = {}
    for entry in manifest['arrays']:
        data = raw[entry['offset']:entry['offset'] + entry['byte_length']]
        code = searchbundle.DTYPES[entry['dtype']][0]
        vals = struct.unpack(f'<{entry["count"]}{code}', data)
        arrays[entry['name']] = {
            'dtype': entry['dtype'], 'count': entry['count'],
            'offset': entry['offset'],
            'sha256': hashlib.sha256(data).hexdigest(),
            'first': _v(vals[0]) if vals else None,
            'last': _v(vals[-1]) if vals else None,
        }
    return {
        'id': name, 'dir': rel, 'version': manifest['version'],
        'content_hash': manifest['content_hash'],
        'compression': manifest['encoding']['compression'],
        'regions': list(b.problem.ids),
        'runs': [{'id': r.id, 'kind': r.kind, 'n_events': r.trace.n_events,
                  'summary': r.trace.summary} for r in b.runs],
        'arrays': arrays,
    }


def build():
    """Return the expectations file's text."""
    names = sorted(os.listdir(os.path.join(common.REPO, FIXTURES)))
    data = {'note': 'generated by lab_web/tools/make_search_expectations.py',
            'bundles': [expect(n) for n in names]}
    return json.dumps(data, indent=1, sort_keys=True, allow_nan=False) + '\n'


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split('\n\n')[0])
    ap.add_argument('--check', action='store_true')
    args = ap.parse_args(argv)
    text = build()
    if args.check:
        same = os.path.exists(OUT) and open(OUT).read() == text
        print('search_expected.json', 'up to date' if same else 'STALE')
        return 0 if same else 1
    with open(OUT, 'w') as f:
        f.write(text)
    print('wrote', OUT)
    return 0


if __name__ == '__main__':
    sys.exit(main())
