# Copyright 2026 Gautham Anil
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Write what lab_web's Lab 5 decoders must reproduce, from coco_lab.

``test/golden/move_expected.json``: for each golden Lab 5 bundle
(``coco_lab/test/fixtures/move_bundles``) its schema, version and content
hash, and for EVERY array its count, the sha256 of its little-endian bytes
and its first and last values (``nan`` as the string ``"nan"``); for a
replan bundle its summary and round count, for a drive bundle each run's
id, controller, outcome and metrics. Regenerated byte for byte by
``test_tools.py``, so it cannot drift.

Usage (``coco_lab`` importable, no ROS)::

    python3 lab_web/tools/make_move_expectations.py [--check]
"""

import argparse
import hashlib
import json
import math
import os
import struct
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from coco_lab import movebundle  # noqa: E402
import common  # noqa: E402

FIXTURES = os.path.join('coco_lab', 'test', 'fixtures', 'move_bundles')
OUT = os.path.join(common.LAB_WEB, 'test', 'golden', 'move_expected.json')


def _v(x):
    if isinstance(x, float) and math.isnan(x):
        return 'nan'
    if isinstance(x, float) and math.isinf(x):
        return 'inf' if x > 0 else '-inf'
    return x


def expect(name):
    """Return the expectation record of one golden Lab 5 bundle."""
    rel = os.path.join(FIXTURES, name)
    path = os.path.join(common.REPO, rel)
    schema = movebundle.ensure(path)
    if schema == movebundle.REPLAN_SCHEMA:
        manifest = movebundle.replay_replan(path)
    else:
        manifest = movebundle.replay_drive(path)
    _, raw = movebundle._read(path, schema)
    arrays = {}
    for entry in manifest['arrays']:
        data = raw[entry['offset']:entry['offset'] + entry['byte_length']]
        code = movebundle.DTYPES[entry['dtype']][0]
        vals = struct.unpack(f'<{entry["count"]}{code}', data)
        arrays[entry['name']] = {
            'dtype': entry['dtype'], 'count': entry['count'],
            'sha256': hashlib.sha256(data).hexdigest(),
            'first': _v(vals[0]) if vals else None,
            'last': _v(vals[-1]) if vals else None,
        }
    out = {'id': name, 'dir': rel, 'schema': schema,
           'version': manifest['version'],
           'content_hash': manifest['content_hash'],
           'compression': manifest['encoding']['compression'],
           'arrays': arrays}
    if schema == movebundle.REPLAN_SCHEMA:
        out['summary'] = manifest['summary']
        out['rounds'] = len(manifest['rounds'])
    else:
        out['runs'] = [{k: r[k] for k in ('id', 'controller', 'outcome',
                                          'metrics')}
                       for r in manifest['runs']]
    return out


def build():
    """Return the expectations file's text."""
    names = sorted(os.listdir(os.path.join(common.REPO, FIXTURES)))
    data = {'note': 'generated by lab_web/tools/make_move_expectations.py',
            'bundles': [expect(n) for n in names]}
    return json.dumps(data, indent=1, sort_keys=True, allow_nan=False) + '\n'


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split('\n\n')[0])
    ap.add_argument('--check', action='store_true')
    args = ap.parse_args(argv)
    text = build()
    if args.check:
        same = os.path.exists(OUT) and open(OUT).read() == text
        print('move_expected.json', 'up to date' if same else 'STALE')
        return 0 if same else 1
    with open(OUT, 'w') as f:
        f.write(text)
    print('wrote', OUT)
    return 0


if __name__ == '__main__':
    sys.exit(main())
