# Copyright 2026 Gautham Anil
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Lab 1's teaching maps: 20 x 20, each built to show one thing.

Every fixture carries its purpose and the claim it exists to demonstrate,
and ``test/test_teaching.py`` checks each claim against the algorithms and
a networkx oracle -- a fixture whose claim stopped being true would fail,
not quietly teach something else.

A fixture is a map plus a start and a goal. The move model is NOT part of
the map (see :mod:`coco_lab.maps`); ``run`` holds the move model the
fixture is meant to be searched under, and a lesson may override it.
"""

from dataclasses import dataclass, field
from typing import Dict, Optional, Tuple

from .maps import LabMap

Cell = Tuple[int, int]


@dataclass(frozen=True)
class Fixture:
    """One teaching map: what it is for, and how to search it."""

    name: str
    purpose: str
    claim: str
    text: str
    run: Dict[str, object] = field(default_factory=dict)
    cost: Optional[Tuple[Tuple[Cell, Cell, float], ...]] = None

    def load(self) -> Tuple[LabMap, Cell, Cell]:
        """Return ``(map, start, goal)``; the map's id is ``teaching/<name>``."""
        m, marks = LabMap.from_ascii(self.text,
                                     map_id=f'teaching/{self.name}')
        if self.cost is not None:
            layer = [0.0] * (m.width * m.height)
            for (r0, c0), (r1, c1), value in self.cost:
                for r in range(r0, r1 + 1):
                    for c in range(c0, c1 + 1):
                        layer[r * m.width + c] = value
            m = LabMap(m.width, m.height, m.occupancy, layer, map_id=m.id)
        return m, marks['S'], marks['G']


FIXTURES: Dict[str, Fixture] = {}


def _add(fixture: Fixture) -> None:
    FIXTURES[fixture.name] = fixture


_add(Fixture(
    name='open',
    purpose='An empty room: the cleanest picture of how differently '
            'Dijkstra and A* spread.',
    claim='Every optimal algorithm returns the same cost, and A* expands '
          'far fewer states than Dijkstra.',
    text="""
        ....................
        ....................
        ....................
        ....................
        .................G..
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
        ..S.................
        ....................
        ....................
        ....................
        ....................
    """,
    run={'connectivity': 8},
))

_add(Fixture(
    name='corridor',
    purpose='A single winding corridor: there is exactly one way through, '
            'so every algorithm must find the same path.',
    claim='All five algorithms return the same path.',
    text="""
        ####################
        #S.................#
        ##################.#
        #..................#
        #.##################
        #..................#
        ##################.#
        #..................#
        #.##################
        #..................#
        ##################.#
        #..................#
        #.##################
        #..................#
        ##################.#
        #..................#
        #.##################
        #..................#
        ##################G#
        ####################
    """,
    run={'connectivity': 8},
))

_add(Fixture(
    name='wall_one_gap',
    purpose='A wall with one gap far from the straight line: the heuristic '
            'points the wrong way until the gap is found.',
    claim='A* is still optimal, but its saving shrinks: it expands more '
          'than half as many states as Dijkstra here, against under a '
          'fifth on the open map.',
    text="""
        ..........#.........
        ..........#.........
        ....................
        ..........#.........
        ..........#.........
        ..........#.........
        ..........#.........
        ..........#.........
        ..........#.........
        ..........#.........
        ..........#.........
        ..........#.........
        ..........#.........
        ..........#.........
        ..........#.........
        ..........#.........
        ..........#.........
        ...S......#.....G...
        ..........#.........
        ..........#.........
    """,
    run={'connectivity': 8},
))

_add(Fixture(
    name='two_routes',
    purpose='A block with a route above and a shorter route below: the '
            'optimal algorithms must pick the shorter one.',
    claim='Dijkstra and A* pass below the block, whose route is cheaper '
          'than the best route above it.',
    text="""
        ....................
        ....................
        ........####........
        ........####........
        ........####........
        ........####........
        ........####........
        ........####........
        ........####........
        ........####........
        ..S.....####.....G..
        ........####........
        ........####........
        ........####........
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
    """,
    run={'connectivity': 8},
))

_add(Fixture(
    name='greedy_trap',
    purpose='A cup that opens toward the start: greedy best-first follows '
            'the heuristic into it.',
    claim='Greedy best-first returns a path strictly costlier than the '
          'optimum; A* returns the optimum.',
    text="""
        ....................
        ....................
        ....................
        ....................
        ....................
        ......#######.......
        ............#.......
        ............#.......
        ............#.......
        ............#.......
        ..S.........#....G..
        ............#.......
        ............#.......
        ............#.......
        ............#.......
        ......#######.......
        ....................
        ....................
        ....................
        ....................
    """,
    run={'connectivity': 8},
))

_add(Fixture(
    name='diagonal_leak',
    purpose='A wall of cells that touch only at their corners: whether it '
            'is a wall depends on the corner-cutting rule.',
    claim='With corner cutting off the optimum goes around the wall; with '
          'it on the path squeezes through and is strictly cheaper. With '
          '4-connectivity the optimum is costlier than with 8.',
    text="""
        ....................
        ....................
        ..#.................
        ...#................
        ....#..........G....
        .....#..............
        ......#.............
        .......#............
        ........#...........
        .........#..........
        ..........#.........
        ...........#........
        ............#.......
        .............#......
        ..............#.....
        ....S..........#....
        ................#...
        .................#..
        ..................#.
        ...................#
    """,
    run={'connectivity': 8, 'corner_cutting': False},
))

_add(Fixture(
    name='no_path',
    purpose='The goal is walled in: there is no path, and every algorithm '
            'must say so rather than invent one.',
    claim='All five algorithms report no_path.',
    text="""
        ....................
        ....................
        ....................
        ....................
        ............#####...
        ............#...#...
        ............#.G.#...
        ............#...#...
        ............#####...
        ....................
        ....................
        ....................
        ..S.................
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
    """,
    run={'connectivity': 8},
))

_add(Fixture(
    name='cost_field',
    purpose='No walls, but a costly band across the straight line with a '
            'cheap gap below it: cost, not distance, decides the route.',
    claim='With the cost layer the optimum detours through the gap; '
          'with cost_weight 0 it crosses the band, and it costs more under '
          'the cost layer than the detour does.',
    text="""
        ....................
        ....................
        ....................
        ..S..............G..
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
    """,
    run={'connectivity': 8, 'cost_weight': 2.0},
    cost=(((0, 6), (19, 13), 252.0), ((8, 6), (10, 13), 0.0)),
))


_add(Fixture(
    name='turn_trap',
    purpose='One crate straight ahead, and a turn penalty: when the cost '
            'of the next move depends on how you arrived, the heading has '
            'to be part of the search state.',
    claim="The ISRO simulator's cell-only A* and Dijkstra both return a "
          'path one turn penalty (0.1) costlier than the optimum that the '
          '(cell, heading) search finds: at (6, 2) the arrivals heading '
          'north-west and north tie at g = 3 + 3*sqrt(2) + 0.1, the cell '
          'keeps the first, and going on north then costs a turn.',
    text="""
        ....................
        ....................
        ....................
        ..G.................
        ....................
        ....................
        ....................
        ....................
        .....#..............
        ....................
        ....................
        ....................
        .....S..............
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
    """,
    run={'turn_penalty': 0.1, 'corner_cutting': True},
))


def load(name: str) -> Tuple[LabMap, Cell, Cell]:
    """Return ``(map, start, goal)`` for the fixture called ``name``."""
    try:
        return FIXTURES[name].load()
    except KeyError:
        raise KeyError(f'no teaching fixture {name!r}; '
                       f'have {sorted(FIXTURES)}') from None
