// Copyright 2026 Gautham Anil
// SPDX-License-Identifier: Apache-2.0

/**
 * Which stdlib files does the Arena actually import? (M1.5 cold start)
 *
 *   node tools/perf/stdlib_usage.mjs [--write tools/arena_stdlib.txt]
 *
 * Boots Pyodide-in-Node with the FULL python_stdlib.zip, installs coco_lab
 * and the Arena glue the way the worker does, runs every planner, teleop,
 * STOP, reset and an input error (so traceback formatting is exercised),
 * then lists every module whose file came from the stdlib zip, as zip
 * entry names. That list (plus each imported package's __init__) is what
 * the trimmed zip keeps; anything not imported here is dropped. A module
 * imported later, on a path this run did not take, would fail with
 * ModuleNotFoundError -- which is why test/arena_worker.test.ts runs the
 * Arena on the trimmed zip too.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadPyodide } from 'pyodide';

const here = dirname(fileURLToPath(import.meta.url));
const web = join(here, '..', '..');
const repo = join(web, '..');
const i = process.argv.indexOf('--write');

const py = await loadPyodide({ indexURL: join(web, 'node_modules', 'pyodide') + '/' });
const zipName = py.runPython("import sys; [p for p in sys.path if p.endswith('.zip')][0]");
const before = py.runPython('import sys; sorted(sys.modules)').toJs();

// coco_lab's sources, as the worker unpacks them
const { readdirSync, statSync } = await import('node:fs');
const src = join(repo, 'coco_lab', 'coco_lab');
const walk = (d) => readdirSync(d).flatMap((n) => { const p = join(d, n); return statSync(p).isDirectory() ? (n === '__pycache__' ? [] : walk(p)) : [p]; });
for (const f of walk(src).filter((p) => p.endsWith('.py'))) {
  const dst = `/home/pyodide/coco_lab/${f.slice(src.length + 1)}`;
  py.FS.mkdirTree(dirname(dst));
  py.FS.writeFile(dst, readFileSync(f));
}
py.FS.writeFile('/home/pyodide/arena_glue.py', readFileSync(join(web, 'src', 'arena', 'arena_glue.py')));
py.globals.set('SPEC', readFileSync(join(repo, 'worlds', 'coco_arena_v1.json'), 'utf-8'));
py.globals.set('post', () => {});
py.runPython(`
import sys, json
sys.path.insert(0, '/home/pyodide')
import arena_glue
world, occ = arena_glue.init(SPEC, 7, 'astar', post, 512)
for k, p in enumerate(json.loads(world)['planners']):
    arena_glue.step(json.dumps([{'tick': 2 * k, 'kind': 'planner', 'choice': p},
                                {'tick': 2 * k, 'kind': 'goal', 'x': 3.0, 'y': 1.0}]))
    arena_glue.step('[]')
t = json.loads(arena_glue.step('[]')[0])['tick']
arena_glue.step(json.dumps([{'tick': t, 'kind': 'teleop', 'linear': 0.3, 'angular': 0.2}]))
arena_glue.step(json.dumps([{'tick': t + 1, 'kind': 'stop'}]))
arena_glue.step(json.dumps([{'tick': t + 2, 'kind': 'reset'}]))
try:
    arena_glue.step(json.dumps([{'tick': 0, 'kind': 'fly'}]))
except Exception:
    import traceback
    traceback.format_exc()
`);
// a Python error crossing into JavaScript is formatted by pyodide itself
try { py.runPython("raise ValueError('probe')"); } catch { /* expected */ }

const mods = py.runPython(`
import sys
z = ${JSON.stringify(zipName)} + '/'
out = set()
for name, m in list(sys.modules.items()):
    f = getattr(m, '__file__', None) or ''
    if f.startswith(z):
        out.add(f[len(z):])
sorted(out)
`).toJs();
const lines = [
  '# The stdlib files the Arena imports (python_stdlib.zip entry names).',
  '# GENERATED by tools/perf/stdlib_usage.mjs from a Pyodide-in-Node run of',
  '# the worker path (every planner, teleop, STOP, reset, an input error and',
  '# a Python error crossing into JavaScript). build_arena_assets.mjs keeps',
  `# exactly these. Pyodide ${py.version}; ${before.length} modules loaded at boot.`,
  ...mods,
];
console.log(`${mods.length} stdlib files imported`);
if (i > 0) writeFileSync(join(web, process.argv[i + 1]), lines.join('\n') + '\n');
